apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vr11
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-vr11@sha256:3d96082dd6d4a7431a47e14e957424a47310acf04ecaf24651e60508e08922c4
        name: my-nodejs
        resources: {}
status: {}
